### ISSUE TITLE
@inkline/nuxt - npm install fail

### ISSUE THREAD

**Issue by danrocha** [inkline/inkline#144]
* **I'm submitting a:**

  - [X] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**

Cannot install using:

`npm i -S @inkline/nuxt`

Results:

```log
168 verbose stack Error: @inkline/nuxt@1.21.3 postinstall: `cd tests/app && npm install`
168 verbose stack Exit status 1
168 verbose stack     at EventEmitter.<anonymous> (/Users/danroc/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
168 verbose stack     at EventEmitter.emit (events.js:305:20)
168 verbose stack     at ChildProcess.<anonymous> (/Users/danroc/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
168 verbose stack     at ChildProcess.emit (events.js:305:20)
168 verbose stack     at maybeClose (internal/child_process.js:1028:16)
168 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
169 verbose pkgid @inkline/nuxt@1.21.3
170 verbose cwd /Users/danroc/Documents/Projects/@remote-architects-club/frontend
171 verbose Darwin 18.7.0
172 verbose argv "/Users/danroc/.nvm/versions/node/v13.5.0/bin/node" "/Users/danroc/.nvm/versions/node/v13.5.0/bin/npm" "install" "--save" "@inkline/nuxt"
173 verbose node v13.5.0
174 verbose npm  v6.14.2
175 error code ELIFECYCLE
176 error errno 1
177 error @inkline/nuxt@1.21.3 postinstall: `cd tests/app && npm install`
177 error Exit status 1
178 error Failed at the @inkline/nuxt@1.21.3 postinstall script.
178 error This is probably not a problem with npm. There is likely additional logging output above.
179 verbose exit [ 1, true ]
```

Tried with versions 1.21.2 and 1.21.1 and both **do not work**.

However:

**v1.21.0 installs with no problems.**

```
+ @inkline/nuxt@1.21.0
added 4 packages from 4 contributors and audited 902691 packages in 37.678s
```

**Comment by alexgrozav** [comment]
Thank you for reporting this. I'll remove postinstall script.

**Comment by alexgrozav** [comment]
Can you please try 1.21.4 and tell me if it fixes the error?

**Comment by danrocha** [comment]
it works fine now, thank you.
