### ISSUE TITLE
Nuxt.js Installation Guide not working

### ISSUE THREAD

**Issue by milaan-muc** [inkline/inkline#254]
Hi,

i have tried to install inkline with your new installation guide but its not working. At the end you talk about editing files in src folder which is not existing. It looks like you just copied over the guide from vue?!?!

**Comment by alexgrozav** [comment]
Hey! Thank you for letting me know. I'm looking into it!

**Comment by milaan-muc** [comment]
How should i install with Nuxt correctly?

I have tried the following in nuxt.config.ts:

```
export default defineNuxtConfig({
	modules: ['@inkline/inkline']
})
```

But that throws an error:

```
 ERROR  Cannot start nuxt:  Nuxt module should be a function: [object Module]                                                        11:37:59

  at installModule (node_modules/@nuxt/kit/dist/index.mjs:338:11)
  at initNuxt (node_modules/nuxt3/dist/index.mjs:1043:13)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6724:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6763:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:384:7)
```

**Comment by alexgrozav** [comment]
Nuxt 3 has an entirely different module definition markup. I'm almost done with the update. Should be up in a couple of hours! :)

**Comment by alexgrozav** [comment]
@milaan-muc I've released a new version of `@inkline/nuxt` that's compatible with Nuxt 3. Can you please try it out and let me know if you encounter any issues? 

https://inkline.io/docs/introduction/installation/nuxt

**Comment by milaan-muc** [comment]
> @milaan-muc I've released a new version of `@inkline/nuxt` that's compatible with Nuxt 3. Can you please try it out and let me know if you encounter any issues?
> 
> https://inkline.io/docs/introduction/installation/nuxt

Thank you but it's not working...

 ```
ERROR  Cannot start nuxt:  Cannot find module '@inkline/nuxt'                                                                       17:35:14
Require stack:
- /Users/tobias/Documents/Repository/ProjectX/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function.p [as resolve] (node_modules/jiti/dist/jiti.js:1:52925)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:221:29)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:333:18)
  at initNuxt (node_modules/nuxt3/dist/index.mjs:1045:13)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6724:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6763:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:384:7)
```

**Comment by alexgrozav** [comment]
Can you copy your **package.json** contents here?

**Comment by milaan-muc** [comment]
Sure...

```
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "nuxt3": "latest",
    "sass": "^1.48.0"
  },
  "dependencies": {
    "@inkline/inkline": "^3.0.6",
    "crypto-js": "^4.1.1"
  }
}
```

**Comment by alexgrozav** [comment]
It looks like `@inkline/nuxt` isn't listed as a dependency. Did you `npm install --save @inkline/nuxt`?

**Comment by milaan-muc** [comment]
I did `npm install --save @inkline/inkline` as shown in your nuxt docu.

![image](https://user-images.githubusercontent.com/3469112/150313765-2f304a07-bf96-4990-926d-2809883e6127.png)

**Comment by alexgrozav** [comment]
So sorry, I didn't realize I missed the `@inkline/nuxt` part from the docs. The command should be 

~~~bash
npm install --save @inkline/inkline @inkline/nuxt
~~~

**Comment by milaan-muc** [comment]
That did it :-) Thank you!

**Comment by alexgrozav** [comment]
Awesome! Let me know if you run into any issues. :)
