### ISSUE TITLE
Failed to resolve component: i-layout-content

### ISSUE THREAD

**Issue by milaan-muc** [inkline/inkline#255]
I'm getting component errors when using components which are to be used as nested components.

For example in my index.vue Pages file this is working:

```
<template>
  <i-layout>
    <p>Test</p>
  </i-layout>
</template>
```

This is not working:

```
<template>
  <i-layout>
    <i-layout-content>
      <p>Test</p>
    </i-layout-contents>
  </i-layout>
</template>
```
It throws the following error:

```
[Vue warn]: Failed to resolve component: i-layout-content
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Invalid value used as weak map key
  at WeakMap.set (<anonymous>)
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3382:11)
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6838:23)
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:3793:31)
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:17)

```

**Comment by alexgrozav** [comment]
Hey! Great find, I forgot that prefixing is now the default option. I've released `@inkline/nuxt@3.0.2` to address this issue.

**Comment by alexgrozav** [comment]
@all-contributors please add @milaan-muc for test

**Comment by milaan-muc** [comment]
Working. Thank you!
