### ISSUE TITLE
[4.0.0-beta] INavbar / IHamburgerMenu: nuxt cannot find \node_modules\@inkline\inkline\composables

### ISSUE THREAD

**Issue by thunfisch987** [inkline/inkline#335]
* **What is the expected and current behavior?**
  When using INavbar Nuxt3 spits out the error:
```
[nuxt] [request error] [unhandled] [500] Cannot find module 'C:\[path to app}\node_modules\@inkline\inkline\composables'                                             07:10:02
  at createEsmNotFoundErr (node:internal/modules/cjs/loader:1060:15)
  at finalizeEsmResolution (node:internal/modules/cjs/loader:1053:15)
  at trySelf (node:internal/modules/cjs/loader:514:12)
  at Module._resolveFilename (node:internal/modules/cjs/loader:1016:24)
  at Module._load (node:internal/modules/cjs/loader:885:27)
  at Module.require (node:internal/modules/cjs/loader:1105:19)
  at require (node:internal/modules/cjs/helpers:103:18)
  at C:\[path to app]\node_modules\@inkline\inkline\components\IHamburgerMenu\IHamburgerMenu.vue:11:20
  at ViteNodeRunner.directRequest (/C:/[path to app]/node_modules/vite-node/dist/client.mjs:285:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (repeated 2 times)
```

* **Steps to reproduce**
  start a normal nuxt 3 project and install inkline 4.0.0-beta.2, then use the INavbar component in app.vue.

* **Please tell us about your environment:**
    - Version: >=4.0.0-beta.2
    - Browser: all
    - Language: TypeScript

* **Other information**
  `C:\[path to app]\node_modules\@inkline\inkline\components\IHamburgerMenu\IHamburgerMenu.vue:11:20`
  corresponds to
  `var _composables = require("@inkline/inkline/composables");`

**Comment by alexgrozav** [comment]
Hey! Thanks for the update. Released `4.0.0-beta.3` that should fix this. Can you please confirm?

**Comment by thunfisch987** [comment]
i'll try it right now!

**Comment by thunfisch987** [comment]
Did not fully fix it, now it has another error:
```
[nuxt] [request error] [unhandled] [500] Cannot find module 'C:\Users\Oliver\Desktop\maguronetwork3\node_modules\@inkline\inkline\i18n\messages\en'                       08:04:04
  at createEsmNotFoundErr (node:internal/modules/cjs/loader:1060:15)  
  at finalizeEsmResolution (node:internal/modules/cjs/loader:1053:15)  
  at trySelf (node:internal/modules/cjs/loader:514:12)  
  at Module._resolveFilename (node:internal/modules/cjs/loader:1016:24)  
  at Module._load (node:internal/modules/cjs/loader:885:27)  
  at Module.require (node:internal/modules/cjs/loader:1105:19)  
  at require (node:internal/modules/cjs/helpers:103:18)  
  at Object.<anonymous> (C:\Users\Oliver\Desktop\maguronetwork3\node_modules\@inkline\inkline\i18n\index.js:13:11)
  at Module._compile (node:internal/modules/cjs/loader:1218:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
```
